"""Deterministic Prioritization Policy for Failure Clusters (Stage 31 Section 6).

Selects the single highest-value failure cluster using a strict lexicographic rule:
1. Eligible completed live failure count (descending)
2. Unique affected task count (descending)
3. Unique repository coverage (descending)
4. Deterministic cluster_id (ascending tie-breaker)

If no eligible completed live failures exist (as in the current local host environment),
selection deterministically returns (None, "NO_ACTIONABLE_LIVE_FAILURES").
"""

from __future__ import annotations

from typing import List, Optional, Tuple

from local.dashboard.models import EvidenceMode
from local.fdd.models import FailureCluster


STATUS_SELECTED = "SELECTED"
STATUS_NO_ACTIONABLE_LIVE = "NO_ACTIONABLE_LIVE_FAILURES"
STATUS_NO_ACTIONABLE = "NO_ACTIONABLE_FAILURES"
STATUS_EMPTY = "NO_CLUSTERS"


def select_highest_value_cluster(
    clusters: List[FailureCluster],
    require_live: bool = True,
) -> Tuple[Optional[FailureCluster], str]:
    """Deterministically selects the highest-value failure cluster.

    Args:
        clusters: List of clusters generated by failure clustering.
        require_live: If True (production default), only clusters with completed
            LIVE actionable failures are eligible. If False (fixture/testing mode),
            actionable fixture failures are also eligible.

    Returns:
        (selected_cluster, selection_status)
    """
    if not clusters:
        return None, STATUS_EMPTY

    if require_live:
        # Filter to clusters containing live actionable runs
        live_actionable = [
            c for c in clusters
            if c.is_actionable and EvidenceMode.LIVE.value in c.evidence_modes
        ]
        if not live_actionable:
            return None, STATUS_NO_ACTIONABLE_LIVE
        eligible_pool = live_actionable
    else:
        # Fixture / testing mode allows fixture actionable clusters
        actionable = [c for c in clusters if c.is_actionable]
        if not actionable:
            return None, STATUS_NO_ACTIONABLE
        eligible_pool = actionable

    # Sort lexicographically:
    # 1. eligible_completed_run_count (descending)
    # 2. unique_tasks_count (descending)
    # 3. unique repository coverage (descending)
    # 4. cluster_id (ascending tie-breaker)
    ranked = sorted(
        eligible_pool,
        key=lambda c: (
            -c.eligible_completed_run_count,
            -c.unique_tasks_count,
            -len(c.repositories),
            c.cluster_id,
        ),
    )

    return ranked[0], STATUS_SELECTED
